[package]
name = "aoc_2022"
description = "Advent of Code 2022 solved with Rust for learning purposes"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-integer = "0.1"
regex="1.7.0"
